### ISSUE TITLE
[BUG] pod cannot mount to PVC of dataset, the error:"Volume has not been added to the list of VolumesInUse in the node's volume status for volume"

### ISSUE THREAD

**Issue by umialpha** [fluid-cloudnative/fluid#1112]
**What is your environment(Kubernetes version, Fluid version, etc.)**
fluid 0.6
**Describe the bug**
When applying a pod using fluid pv/pvc, the pod fails to start, it shows following mesaages when `kubectl describe pod mypod`

```
Unable to mount volumes for pod "mypod": timeout expired waiting for volumes to attach or mount for pod "maincv"/"mypod". list of unmounted volumes=[localalluxio]. list of unattached volumes=[localalluxio default-token-jrxmp]
```
`localalluxio` is the dataset pvc.

I check the log of kubelet on the assigning node, get this error message.
```
Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"maincv-ziyue-test\" (UniqueName: \"kubernetes.io/csi/fuse.csi.fluid.io^maincv-ziyue-test\") pod \"mypod\" (UID: \"8732e97e-4ef5-46ba-874d-08ebedd7ec9c\") 
```

But I `kubectl get node NODENAME -o yaml`, it shows:

```
  volumesInUse:
  - kubernetes.io/csi/fuse.csi.fluid.io^maincv-ziyue-test
```

**Comment by cheyang** [comment]
I think it's due to Kubelet's configuration. Please check the doc: https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/userguide/faq.md#4-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E5%88%9B%E5%BB%BA%E4%BB%BB%E5%8A%A1%E6%8C%82%E8%BD%BD-runtime-%E5%88%9B%E5%BB%BA%E7%9A%84-pvc-%E7%9A%84%E6%97%B6%E5%80%99%E5%87%BA%E7%8E%B0-driver-name-fusecsifluidio-not-found-in-the-list-of-registered-csi-drivers-%E9%94%99%E8%AF%AF

**Comment by cheyang** [comment]
@umialpha if you agree, I will close this issue. Thanks.

**Comment by umialpha** [comment]
@cheyang  thanks, It turns out to be my kubelet problem, it is too old to support csi plugins
