### ISSUE TITLE
alluxio worker is not scheduled to the intended node

### ISSUE THREAD

**Issue by ssz1997** [fluid-cloudnative/fluid#1296]
Fluid version: master
Alluxio version: 2.7.0
k8s version: 1.20

I was following https://github.com/fluid-cloudnative/community/blob/master/testcase/fluid-testcase.md#%E6%89%A9%E5%AE%B9alluxioruntime, and the newly created worker is scheduled on node2, not node1. 

When replica is 1:
![image](https://user-images.githubusercontent.com/32376495/146805728-9b6c24f7-ed59-4142-b039-8ad975b44bb4.png)
worker-0 is on ip-10-0-5-77.ec2.internal,
2 nginx pods are on  ip-10-0-6-232.ec2.internal,
1 nginx pod is on ip-10-0-4-247.ec2.internal

Ran `kubectl edit alluxiorutime hbase` to modify the `.spec.replicas` to 2:
![image](https://user-images.githubusercontent.com/32376495/146806036-137352cc-4aca-4499-adbd-db2930c30973.png)
Worker-1 is scheduled on ip-10-0-4-247.ec2.internal, not the pod with 2 nginx pods. 

Is this expected behavior?

**Comment by cheyang** [comment]
The logic of placing worker is not about the number of app pods(using dataset), because we can't predict if there are two pods on the same node, it can consume more data throughput.   It's about one or nothing. we prefer the nodes which the app pods(using dataset) locates rather than no app pods(using dataset).

**Comment by ssz1997** [comment]
Thanks for the clarification. Previously I was lucky to see that the new worker happened to be scheduled to the node with 2 app pods.
