### ISSUE TITLE
[BUG] Followed steps in accelerate_data_accessing example, but no files can be list out

### ISSUE THREAD

**Issue by xuning97** [fluid-cloudnative/fluid#538]
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:11:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
Fluid version: 0.4.0

**Describe the bug**
trying http://pasa-bigdata.nju.edu.cn/fluid/accelerate_data_accessing.html with aliyun ECSs, it seems everything works fine.
But at the last step, nginx cannot find any data at /data

![image](https://user-images.githubusercontent.com/1954442/104559896-0b47f580-5680-11eb-83c7-f3e1b3577f78.png)

![image](https://user-images.githubusercontent.com/1954442/104560328-ae990a80-5680-11eb-9f53-cd2bf5c7582d.png)

![image](https://user-images.githubusercontent.com/1954442/104560387-c2dd0780-5680-11eb-9264-6832bb0334e4.png)

**What you expect to happen:**
I can see file list under nginx, /data folder

**How to reproduce it**
Dev can check the env. It's reproducible under that env with the steps described in the doc

**Additional Information**
[diagnose_fluid_1610588911.tar.gz](https://github.com/fluid-cloudnative/fluid/files/5813040/diagnose_fluid_1610588911.tar.gz)

**Comment by njuwelkin** [comment]
I'm following the same step, however I get below errir when creating the alluxioRuntime.
`
$ kubectl describe alluxioruntime
....
Events:
  Type     Reason               Age                From            Message
  ----     ------               ----               ----            -------
  Warning  ErrorProcessRuntime  14m (x2 over 14m)  AlluxioRuntime  Failed to setup ddc engine due to error execute command [alluxio fs mount /spark https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/stable/] with expectedErr: command terminated with exit code 255 stdout Ufs path https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/stable does not exist and stderr
`

**Comment by yangyuliufeng** [comment]
the name and the mountpoint are in the same level
the pod need to be able to connect the network

**Comment by xuning97** [comment]
issue solved, thanks
